rule headers:
    output: "HEADERS.txt"
    message: "Downloading {output}"
    shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/HEADERS.txt"

rule nne:
    output: "CRND0103-2020-AK_Aleknagik_1_NNE.txt"
    message: "Downloading {output}"
    shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2020/CRND0103-2020-AK_Aleknagik_1_NNE.txt"

rule plot_r:
    input: headers="HEADERS.txt", nne="CRND0103-2020-AK_Aleknagik_1_NNE.txt"
    output: "Rplot001.png"
    message: "Turning {input.headers} and {input.nne} into {output}"
    shell: """
           module load R
           Rscript plot_files.r HEADERS.txt CRND0103-2020-AK_Aleknagik_1_NNE.txt
           """