locations = [
    "Aleknagik_1_NNE",
    "King_Salmon_42_SE",
    "Fairbanks_11_NE",
    "Sitka_1_NE",
]

rule plot_r:
    input: headers="HEADERS.txt",nne="CRND0103-2020-AK_Aleknagik_1_NNE.txt"
    output: "Rplot001.png"
    message: "Turning {input.headers} and {input.nne} into {output}."
    shell: """
           module load R
           Rscript plot_files.r {input.headers} {input.nne}
           """

rule generate_urls:
    message: "Generating {len(locations)} locations"
    input: expand("{sample}.txt",sample=locations)

rule download_one_data:
    input: "{sample}"
    output: f"{sample}.txt"
    message: "Downloading {output}"
    shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/2020/CRND0103-2020-{sample}.txt"


rule download_headers:
    output: "HEADERS.txt"
    message: "Downloading {output}"
    shell: "wget https://www1.ncdc.noaa.gov/pub/data/uscrn/products/daily01/HEADERS.txt"
